# Generated by Django 5.2.4 on 2025-07-26 22:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_type', models.CharField(choices=[('speed_limit', 'Speed Limit'), ('no_horn', 'No Horn'), ('stop', 'Stop Sign'), ('yield', 'Yield Sign'), ('one_way', 'One Way'), ('no_parking', 'No Parking'), ('other', 'Other')], max_length=20)),
                ('sign_value', models.CharField(blank=True, max_length=50, null=True)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('two_wheeler', 'Two Wheeler'), ('four_wheeler', 'Four Wheeler'), ('commercial', 'Commercial Vehicle')], max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_limit', models.IntegerField(blank=True, null=True)),
                ('actual_speed', models.IntegerField(blank=True, null=True)),
                ('no_horn_zone', models.BooleanField(default=False)),
                ('horn_applied', models.BooleanField(default=False)),
                ('seatbelt_required', models.BooleanField(default=False)),
                ('seatbelt_worn', models.BooleanField(default=False)),
                ('violation_type', models.CharField(choices=[('speed_violation', 'Speed Violation'), ('horn_violation', 'Horn Violation'), ('seatbelt_violation', 'Seatbelt Violation'), ('stop_violation', 'Stop Sign Violation'), ('no_violation', 'No Violation')], default='no_violation', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('violation_description', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('compliance_score', models.IntegerField(default=100)),
                ('driving_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivewise.drivingsession')),
                ('traffic_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivewise.trafficsign')),
            ],
        ),
        migrations.CreateModel(
            name='RewardToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_earned', models.IntegerField(default=0)),
                ('tokens_spent', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivewise.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='drivingsession',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivewise.vehicle'),
        ),
    ]
