# Generated by Django 5.2.4 on 2025-07-26 22:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTrafficSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_type', models.CharField(choices=[('speed_limit', 'Speed Limit'), ('no_horn', 'No Horn'), ('four_wheeler', 'Four Wheeler'), ('seatbelt', 'Seatbelt')], max_length=20)),
                ('speed_limit_value', models.IntegerField(blank=True, help_text='Enter speed limit value (e.g., 40, 60)', null=True)),
                ('no_horn_zone', models.BooleanField(default=False, help_text='Is this a no horn zone?')),
                ('four_wheeler_zone', models.BooleanField(default=False, help_text='Is this a four-wheeler zone?')),
                ('seatbelt_required', models.BooleanField(default=False, help_text='Is seatbelt required?')),
                ('location', models.CharField(blank=True, help_text='Location of the traffic sign', max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
