# Generated by Django 5.2.4 on 2025-07-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewise', '0002_manualtrafficsign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualtrafficsign',
            name='four_wheeler_zone',
        ),
        migrations.RemoveField(
            model_name='manualtrafficsign',
            name='no_horn_zone',
        ),
        migrations.RemoveField(
            model_name='manualtrafficsign',
            name='seatbelt_required',
        ),
        migrations.RemoveField(
            model_name='manualtrafficsign',
            name='speed_limit_value',
        ),
        migrations.AddField(
            model_name='manualtrafficsign',
            name='drive_value',
            field=models.IntegerField(blank=True, help_text='Enter the actual driving value (e.g., actual speed)', null=True),
        ),
        migrations.AddField(
            model_name='manualtrafficsign',
            name='sign_value',
            field=models.CharField(blank=True, help_text="Enter the sign value (e.g., 40 for speed limit, 'Yes' for no horn)", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manualtrafficsign',
            name='sign_type',
            field=models.CharField(choices=[('speed_limit', 'Speed Limit'), ('no_horn', 'No Horn'), ('four_wheeler', 'Four Wheeler'), ('seatbelt', 'Seatbelt')], help_text='Select the type of traffic sign', max_length=20),
        ),
    ]
