# Generated by Django 5.2.4 on 2025-07-26 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewise', '0003_remove_manualtrafficsign_four_wheeler_zone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0, help_text='Current rank in leaderboard')),
                ('total_violations', models.IntegerField(default=0)),
                ('total_trips', models.IntegerField(default=0)),
                ('compliance_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('average_compliance_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('total_tokens_earned', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drivewise.vehicle')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
