# Generated by Django 5.2.4 on 2025-07-27 06:52:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivewise', '0004_leaderboard'),
    ]

    operations = [
        # Add vehicle field to ComplianceRecord if it doesn't exist
        migrations.AddField(
            model_name='compliancerecord',
            name='vehicle',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='drivewise.vehicle',
                help_text='Select the vehicle'
            ),
        ),
        # Add vehicle field to ManualTrafficSign if it doesn't exist
        migrations.AddField(
            model_name='manualtrafficsign',
            name='vehicle',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='drivewise.vehicle',
                help_text='Select the vehicle'
            ),
        ),
    ]
